name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: mikhael7/mikhael7@main
        with:
          WAKATIME_API_KEY: ${{ default.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ default.GH_TOKEN }}
